// ===================================
//  ROTA DE TESTE ( /biblioteca )
###
GET http://localhost:3077/biblioteca
###
// ===================================

// ===================================
//  ROTAS DE USUÁRIOS ( /biblioteca/users )


###
GET http://localhost:3077/biblioteca/users
###

POST http://localhost:3077/biblioteca/users
Content-Type: application/json

{
  "name": "Letícia Fonseca",
  "birthDate": "2004-02-16",
  "sex": "Masculino",
  "adress": "133 Santana de Cataguases, Minas Gerais, Brasil"
}
###
// ===================================



// ===================================
//  ROTAS DE AUTORES ( /biblioteca/authors )
###

POST http://localhost:3077/biblioteca/authors
Content-Type: application/json

{
  "name": "Machado de Assis",
  "birthDate": "1839-06-21",
  "sex": "Masculino",
  "writingGenre": "Poetry"
}
###

GET http://localhost:3077/biblioteca/authors
###

// ===================================


// ===================================
//  ROTAS DE LIVROS ( /biblioteca/books )
###
POST http://localhost:3077/biblioteca/books
Content-Type: application/json

{
  "title": "Livro Machado de Assis",
  "synopsis": "Livro do Machado de Assis",
  "year": 1882,
  "author": "68ffce58e38d3e499eef7b86",
  "isAvailable": true,
  "expectedReturnDate":""
}
###
GET http://localhost:3077/biblioteca/books
###
// ===================================

// ===================================
//  ROTA DE EMPRÉSTIMOS ( /biblioteca/loans )
###
POST http://localhost:3077/biblioteca/loans
Content-Type: application/json

{
  "userId":"68ffce50e38d3e499eef7b83",
  "bookId":"68ffcf1e16b750cbe35a82d4"
}
###

